# Generated by Django 4.1 on 2022-09-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="ContactProfile",),
        migrations.RemoveField(model_name="userprofile", name="skills",),
        migrations.DeleteModel(name="Skill",),
    ]
