# Generated by Django 4.1 on 2022-09-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_contactprofile_remove_userprofile_skills_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Certificate",),
        migrations.DeleteModel(name="Testimonial",),
    ]
